name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK
      uses: actions/setup-java@v6
      with:
        java-version: 21
        distribution: temurin
        cache: maven
        show-download-progress: true

    - name: Build with Maven/Tycho
      run: >
        ./mvnw verify

    - name: Archive Repository
      uses: actions/upload-artifact@v7
      if: ${{ success() }}
      with:
        name: repository-${{ runner.os }}
        path: '**/*.repository/target/repository'
